### ISSUE TITLE
Metalic not working

### ISSUE THREAD

**Issue by Faizur2ndacc** [Metallic-Web/Metallic#12]
When I visited meatllic.gq when I entered url it is showing the address is temporarily not available or permanently shiftee to a new domain

**Comment by Nebelung-Dev** [comment]
Try reloading the page?

**Comment by Nebelung-Dev** [comment]
![image](https://github.com/Metallic-Web/Metallic/assets/81875430/4df2932d-3312-4d6b-8fd1-364094a2792a)
Works for me
