### ISSUE TITLE
website

### ISSUE THREAD

**Issue by FFierce** [Metallic-Web/Metallic#2]
the websites down
![image](https://user-images.githubusercontent.com/88373778/212813662-ae9aea54-c7a6-45da-8220-6af9c89c32c3.png)

**Comment by luckycdev** [comment]
my self hosted one is not working as well  and it was the other day
![image](https://user-images.githubusercontent.com/50680260/212972959-8ce96150-7be6-4f57-977f-acdcb209decf.png)

**Comment by Nebelung-Dev** [comment]
> my self hosted one is not working as well and it was the other day ![image](https://user-images.githubusercontent.com/50680260/212972959-8ce96150-7be6-4f57-977f-acdcb209decf.png)

Theis is just an issue with Ultraviolet. Try reloading or your hosting might not support it

**Comment by SevenworksDev** [comment]
> 

He is self-hosting it. He doesnt host it anywhere besides his computer, also this error occurs when its being hosting without a TOMP server im pretty sure.
