### ISSUE TITLE
This is still occuring.

### ISSUE THREAD

**Issue by FFierce** [Metallic-Web/Metallic#3]
Railway [](https://metalic.gq) still fails to load.

**Comment by FFierce** [comment]
![image](https://user-images.githubusercontent.com/88373778/214469030-0a47289a-e8b1-4bf5-a172-c417613dceb3.png)

**Comment by FFierce** [comment]
- This is the official one (https://metallic.gq)

**Comment by Nebelung-Dev** [comment]
All domains are up
