### ISSUE TITLE
Any possibility a switch to bun would work?

### ISSUE THREAD

**Issue by JarzaCode** [Metallic-Web/Metallic#35]
I'm not recommending you completely redo all of the code, but I've run benchmarks running with bun vs pnpm, and bun is 2x faster. To my understanding, this proxy is heavily speed-focused, and a large increase in that would be great. I have also tested, and changing some things, like tests, to bun-native code, changes the time from around 1 second of testing to 0.02 seconds. I would be willing to help make the transfer, I just would like to know if it could be placed on the roadmap.

Thank you!

**Comment by JarzaCode** [comment]
https://github.com/cognetwork-dev/Metallic/pull/36

**Comment by Nebelung-Dev** [comment]
Although I appreciate the work you put into this I am going to keep it a Node.js project instead of Bun or Deno just because the majority of users use Node.
