### ISSUE TITLE
[Feature Request] put through custom DNS, or list to block specific sites.

### ISSUE THREAD

**Issue by yodaluca23** [Metallic-Web/Metallic#5]
I know that, adding a list of specific sites is supported by UV, but I believe that it would be able to go to those with just using one of the other proxies... also, if we could just have it, put everything through a custom DNS, that could also block websites then that would be way more convenient, because, then we could use like 1.1.1.3, instead of needing to import a giant list of websites...

And if we could make the list (if you add the list option instead of DNS.) use environment variables, so that people can't just view the list and see if their website that they want to go to isn't on it...

**Comment by Nebelung-Dev** [comment]
I will look into adding a blocklist

**Comment by yodaluca23** [comment]
> I will look into adding a blocklist

OK great and if that works out if you could put it in the format of each website per line so that we can easily use pi-hole lists, that would be great! 

And if we could have an option to just put in somewhere a URL to the raw formatting of a pi-hole list 

(the URL for the pi-hole list would preferably be put through the proxy, so that if someone looking through the network logs sees a ping to a pi-hole NSFW website list, that might be suspicious, also so that if the url is blocked it gets unblocked and Metallic is still able to fetch the list.)

that way we can automatically have the list update...

**Comment by Nebelung-Dev** [comment]
I think it works

**Comment by yodaluca23** [comment]
> I think it works

Wheres it in?

**Comment by Nebelung-Dev** [comment]
https://github.com/Metallic-Web/Metallic/blob/main/blocklist/block.json

**Comment by Nebelung-Dev** [comment]
It's json

**Comment by yodaluca23** [comment]
> It's json

Right, so is it like this?

[example.site, example2.site, example3.site]

**Comment by Nebelung-Dev** [comment]
yeah just the hostnames
