### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by binary-pumpkin** [Metallic-Web/Metallic#6]
when I search something or open an app it says TypeError: Failed to fetch.
![Screenshot 2023-03-29 8 37 53 AM](https://user-images.githubusercontent.com/125479258/228537470-a5089b62-f7fe-442b-a677-9eade97c62b9.png)

**Comment by Nebelung-Dev** [comment]
working on something

**Comment by Nebelung-Dev** [comment]
might fix

**Comment by binary-pumpkin** [comment]
PLEASE FIX

**Comment by Theblackmamba824** [comment]
> i use birdfood.gq btw

do u have any other links
