### ISSUE TITLE
All links I have tried either default to a white screen or say "out of range"

### ISSUE THREAD

**Issue by Pendem0nium** [Metallic-Web/Metallic#8]
Metallic has been working great for me for weeks until just a few hours ago, when all of the links I was using completely failed.(https://metallic.eu.org/?fr=, https://blazer.rottenprawn.com/, and https://met.finixp.info/)
![image](https://user-images.githubusercontent.com/128760129/232642279-c50b595c-b6a7-48d5-9a98-650476f7b837.png)
![image](https://user-images.githubusercontent.com/128760129/232642587-ffebbb4e-3298-4023-a993-cd90450bd90b.png)
What could be causing this?

**Comment by bltstudios** [comment]
I am getting a similar error starting around the same time: 
![image](https://user-images.githubusercontent.com/70473279/232758029-83a86edd-b7fb-4ca3-95e4-3c2a065f6acb.png)

**Comment by TechTacoTuesday** [comment]
RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

**Comment by GreenyDEV** [comment]
this has nothing to do with metallics code. it just means the server is down. this issue is invalid.
